#!/bin/bash

# immediately fail if an error occurs
set -e

docker rm -fv gk-couchdb || true
docker run -d -p 5984:5984 --name gk-couchdb klaemo/couchdb:2.0.0

TIMEOUT=60
TRIES=0
printf 'Waiting for CouchDB to be available to us'

until $(curl --output /dev/null --silent --head --fail http://localhost:5984); do
  printf '.'
  TRIES=$TRIES+1

  if [[ $TRIES -eq $TIMEOUT ]]; then
    echo 'Timed out waiting for CouchDB to be available'
    exit 1
  fi

  sleep 1
done
